import Sidebar from "@/component/sidebar/Sidebar";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full flex md:flex-row flex-col">
      <div className="md:w-2/12 w-full md:border-r border-0 md:border-darkBlue/15">
        <Sidebar />
      </div>
      <div className="md:w-10/12 w-full md:p-5 p-2">{children}</div>
    </div>
  );
}
